sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install codeclimate-test-reporter
script:
  - node_modules/.bin/gulp test -c
after_success:
  - node_modules/.bin/codeclimate-test-reporter < .coverage/lcov.info

